### ISSUE TITLE
cxr_reg_weights.hdf5 file does not exist

### ISSUE THREAD

**Issue by zeynepozdemir** [armiro/COVID-CXNet#11]
The hdf5 file to be loaded in the hands_on_covid_cxnet.ipynb file is not available in your github repo. How can I find?
Thanks.

**Comment by armiro** [comment]
Thanks, @zeynepozdemir for reminding me about this. It is now available on [checkpoints/U-Net](https://github.com/armiro/COVID-CXNet/tree/master/checkpoints/U-Net).

**Comment by amitbcp** [comment]
I might have missed it , but does the repo has the script to train the UNET ?
The paper states the datasets used for it though.
Thanks in advance.

**Comment by armiro** [comment]
@amitbcp Nope it doesn't. I have cloned and reran a notebook from Kaggle with its associating datasets ([check it out](https://www.kaggle.com/nikhilpandey360/lung-segmentation-from-chest-x-ray-dataset)) but didn't add it to the repo. You can also find more in Kaggle by searching for _u-net lung segmentation_.

**Comment by amitbcp** [comment]
Thank you so much.
