### ISSUE TITLE
Single Source of Dataset

### ISSUE THREAD

**Issue by amitbcp** [armiro/COVID-CXNet#9]
Thanks for open sourcing the code and research for covid.
As in the paper the the list of CXR datasets are listed. Can you share the aggregated set that was used by you to train along with the final metadata. This would serve as a good starting point to quickly start the experiments and further research.

This section in the Repo : https://github.com/armiro/COVID-CXNet/tree/master/chest_xray_images/covid19
Are these all Covid positive ? Is any metadata file also  available ?

**Comment by armiro** [comment]
Good questions @amitbcp 

- I will provide a single `.npy` file of COVID-19 images as well as a `.zip` one. Other images (CAP and normal) need to be curated more before being provided publicly, thus will be available later. Meanwhile, you can request [CheXpert dataset](https://stanfordmlgroup.github.io/competitions/chexpert/) or download [NIH CXR-14 dataset](https://www.kaggle.com/nih-chest-xrays/data) from their links.
- All the images here are COVID-19 positive cases.
- Metadata is in progress. I have provided a guideline on how to prepare for each image in #3 . Feel free to reach me if you want to contribute. I think metadata will be available within two week.

**Comment by amitbcp** [comment]
Thank you so much @armiro .
I have the CheXpert & NIH datasets already. Sure I'll look into the metadata request you mentioned.
